project:
  type: website
  output-dir: docs
  resources: 
    - "open_card.png"
  
website:
  title: "Low-wage workforce tracker"
  site-url: https://economic.github.io/low_wage_workforce
  image: open_card.png
  open-graph: true
  twitter-card:
    creator: "@benzipperer"
  google-analytics: "G-FY2JEDFR9V"
  search: false
  navbar:
    background: light
    left:
      - href: historical.qmd
        text: Historical trends
      - href: states.qmd
        text: State data
    right:
      - icon: github
        href: https://github.com/economic/low_wage_workforce
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css